data:
  raw_train_csv: D:\Skills\new\NeurIPS2\data\train.csv
  raw_test_csv: D:\Skills\new\NeurIPS2\data\test.csv
  ffv_csv: D:\Skills\new\NeurIPS2\data\train_supplement\FFV.csv
  TC_csv: D:\Skills\new\NeurIPS2\data\train_supplement\TC.csv
  TG_csv : D:\Skills\new\NeurIPS2\data\train_supplement\TG.csv
  test_supplement_csv: D:\Skills\new\NeurIPS2\data\train_supplement\test_supplement.csv

output:
  ffv_merged_csv: D:\Skills\new\NeurIPS2\outputs\csv\ffv_merged.csv
  Tc_csv: D:\Skills\new\NeurIPS2\outputs\csv\Tc_cleaned.csv
  Tg_csv: D:\Skills\new\NeurIPS2\outputs\csv\Tg_cleaned.csv

  rdkit_ffv_meta:  D:\Skills\new\NeurIPS2\outputs\csv\rdkit_ffv_meta.csv
  rdkit_ffv: D:\Skills\new\NeurIPS2\outputs\torch_tensor\rdkit_ffv.pt
  seflies: D:\Skills\new\NeurIPS2\outputs\torch_tensor\selfies.pt

  

models: #pre trained or trained (.pt, .keras, .pkl, .py  etc.)
  